import { TranslationTypes } from 'autoql-fe-utils'

export default [
  // 0. empty response
  { data: {} },
  // 1. only display type returned, nothing else
  {
    data: {
      data: { display_type: 'table' },
    },
  },
  {
    // 2. no data and no display type
    data: {
      data: {
        columns: [],
        display_type: null,
        interpretation: 'all invoices for invoice of this month ',
        query_id: 'q_VzB9irC-RpKY-13XwgHrrw',
        rows: null,
      },
      message: '',
      reference_id: '1.1.210',
    },
  },
  {
    // 3. valid pivot data response
    data: {
      data: {
        columns: [
          {
            type: 'DATE',
            groupable: true,
            active: false,
            name: 'sale__transaction_date__month',
          },
          {
            active: false,
            groupable: false,
            name: 'sale__line_item___sum',
            type: 'DOLLAR_AMT',
          },
        ],
        display_type: 'data',
        interpretation: 'total sales by line item by transaction month',
        query_id: 'q_y4sWT0IAStWnLeM7COEsSQ',
        rows: [
          [1483142400, 12500],
          [1488240000, 8742.68],
          [1490918400, 11723.36],
          [1493510400, 3243.12],
          [1496188800, 14642.19],
        ],
      },
      message: 'Success',
      reference_id: '1.1.210',
    },
  },
  {
    // 4. valid help response
    data: {
      data: {
        columns: [
          {
            type: 'STRING',
            groupable: false,
            active: false,
            name: 'Help Link',
          },
        ],

        active: false,
        groupable: false,
        name: 'Help Link',
        type: 'STRING',
        display_type: 'help',
        interpretation: 'help on bar-chart',
        query_id: 'q_t_LufuRpQsGh71LE51qYnA',
        rows: [['http://chata.ai/userguide/#bar-chart-2']],
      },
      message: 'Success',
      reference_id: '1.1.210',
    },
  },
  {
    // 5. valid suggestion response
    data: {
      data: {
        items: [
          'Total trade size by contract',
          'Total trade size by contract this year',
          'Total trade size by contract for financial conglomerates',
          'Total trade size by contract for zcpbto',
          'None of these',
        ],
        query_id: 'q_NQvh-_v1RBSMZrtP9F7BTQ',
        pagination: {
          page_size: 5,
          total_items: 5,
          total_pages: 1,
          current_page: 1,
          next_url: null,
          previous_url: null,
        },
      },
      message: 'Success',
      reference_id: '1.1.200',
    },
  },
  {
    // 6. valid validation response single suggestion
    data: {
      full_suggestion: [
        {
          start: 10,
          suggestion_list: [{ text: 'Jane Johnson', value_label: 'customer name' }],
          end: 14,
        },
      ],
      query: 'sales for john',
    },
    message: 'Success',
    reference_id: '1.1.210',
  },
  {
    // 7. display type that we dont understand
    data: {
      data: {
        columns: [
          {
            type: 'DATE',
            groupable: true,
            active: false,
            name: 'sale__transaction_date__month',
          },
          {
            active: false,
            groupable: false,
            name: 'sale__line_item___sum',
            type: 'DOLLAR_AMT',
          },
        ],
        display_type: 'unknown_type',
        interpretation: 'total sales by line item by transaction month',
        query_id: 'q_y4sWT0IAStWnLeM7COEsSQ',
        rows: [
          [1483142400, 12500],
          [1488240000, 8742.68],
          [1490918400, 11723.36],
          [1493510400, 3243.12],
          [1496188800, 14642.19],
        ],
      },
      message: 'Success',
      reference_id: '1.1.210',
    },
  },
  {
    // 8. valid regular table data response
    data: {
      data: {
        columns: [
          {
            display_name: 'Quantity',
            type: 'STRING',
            groupable: true,
            active: false,
            is_visible: true,
            name: 'sale__transaction_date__month',
          },
          {
            display_name: 'Amount',
            active: false,
            groupable: false,
            is_visible: true,
            name: 'sale__line_item___sum',
            type: 'DOLLAR_AMT',
          },
        ],
        display_type: 'data',
        interpretation: 'total sales by line item by transaction month',
        query_id: 'q_y4sWT0IAStWnLeM7COEsSQ',
        rows: [
          [1483142400, 12500],
          [1488240000, 8742.68],
          [1490918400, 11723.36],
          [1493510400, 3243.12],
          [1496188800, 14642.19],
        ],
      },
      message: 'Success',
      reference_id: '1.1.210',
    },
  },
  {
    // 9. valid list data
    data: {
      message: 'Success',
      data: {
        sql: [''],
        chart_images: null,
        fe_req: {
          test: false,
          chart_images: 'exclude',
          text: 'all online sales',
          disambiguation: [],
          filters: [],
          orders: [],
          source: 'data_messenger',
          persistent_filter_locks: [],
          session_filter_locks: [],
          translation: TranslationTypes.EXCLUDE,
          page_size: 50,
        },
        display_type: 'data',
        interpretation: "all online sales 'East' (Customer Region)",
        text: 'all online sales',
        columns: [
          {
            display_name: 'Sales Date',
            type: 'DATE',
            multi_series: false,
            is_visible: true,
            name: 'dd_sale.date',
            groupable: false,
          },
          {
            display_name: 'Transaction Number',
            type: 'QUANTITY',
            multi_series: false,
            is_visible: true,
            name: 'online_sales.online_sales_fact.pos_transaction_number',
            groupable: false,
          },
          {
            display_name: 'Customer',
            type: 'STRING',
            multi_series: false,
            is_visible: true,
            name: 'public.customer_dimension.customer_name',
            groupable: false,
          },
          {
            display_name: 'Customer Type',
            type: 'STRING',
            multi_series: false,
            is_visible: true,
            name: 'public.customer_dimension.customer_type',
            groupable: false,
          },
          {
            display_name: 'Customer Region',
            type: 'STRING',
            multi_series: false,
            is_visible: true,
            name: 'public.customer_dimension.customer_region',
            groupable: false,
          },
          {
            display_name: 'Customer State',
            type: 'STRING',
            multi_series: false,
            is_visible: true,
            name: 'public.customer_dimension.customer_state',
            groupable: false,
          },
          {
            display_name: 'Category',
            type: 'STRING',
            multi_series: false,
            is_visible: true,
            name: 'public.product_dimension.category_description',
            groupable: false,
          },
          {
            display_name: 'Department',
            type: 'STRING',
            multi_series: false,
            is_visible: true,
            name: 'public.product_dimension.department_description',
            groupable: false,
          },
          {
            display_name: 'Product Description',
            type: 'STRING',
            multi_series: false,
            is_visible: true,
            name: 'public.product_dimension.product_description',
            groupable: false,
          },
          {
            display_name: 'Quantity',
            type: 'QUANTITY',
            multi_series: false,
            is_visible: true,
            name: 'online_sales.online_sales_fact.sales_quantity',
            groupable: false,
          },
          {
            display_name: 'Online Sales Amount',
            type: 'DOLLAR_AMT',
            multi_series: false,
            is_visible: true,
            name: 'online_sales.online_sales_fact.sales_dollar_amount',
            groupable: false,
          },
          {
            display_name: 'Promotion Name',
            type: 'STRING',
            multi_series: false,
            is_visible: true,
            name: 'public.promotion_dimension.promotion_name',
            groupable: false,
          },
          {
            display_name: 'Coupon Type',
            type: 'STRING',
            multi_series: false,
            is_visible: true,
            name: 'public.promotion_dimension.coupon_type',
            groupable: false,
          },
          {
            display_name: 'Price Reduction Type',
            type: 'STRING',
            multi_series: false,
            is_visible: true,
            name: 'public.promotion_dimension.price_reduction_type',
            groupable: false,
          },
        ],
        rows: [
          [
            1658793600,
            4662670,
            'Thom F. Vogel',
            'Individual',
            'East',
            'MA',
            'Food',
            'Dairy',
            'Brand #381 butter milk',
            8,
            208,
            'Summer Super Sale',
            'Pennysaver',
            '3 for price of 2',
          ],
          [
            1658793600,
            4662677,
            'Tanya U. Sanchez',
            'Individual',
            'East',
            'MA',
            'Medical',
            'Pharmacy',
            'Brand #26 sleeping pills',
            6,
            388,
            'July 4th Cool Sale',
            'Pennysaver',
            'Half Price',
          ],
          [
            1658793600,
            4662702,
            'Robert H. Campbell',
            'Individual',
            'East',
            'TN',
            'Food',
            'Seafood',
            'Brand #403 haddock',
            9,
            314,
            'Winter Cool Promotion',
            'Register Receipt',
            '3 for price of 2',
          ],
          [
            1658793600,
            4662695,
            'William R. Nguyen',
            'Individual',
            'East',
            'SC',
            'Misc',
            'Gifts',
            'Brand #462 electric razor',
            1,
            538,
            'Christmas Discount Sale',
            'Email',
            'Half Price',
          ],
          [
            1658793600,
            4662637,
            'Juanita E. Stein',
            'Individual',
            'East',
            'CT',
            'Non-food',
            'Cleaning supplies',
            'Brand #236 feather duster',
            10,
            487,
            'Summer Super Promotion',
            'Post',
            'Half Price',
          ],
        ],
        session_filter_locks: [],
        query_id: 'q_Bvk6t-xcSR-tmNK9wtKo1Q',
        parsed_interpretation: [
          {
            c_type: 'PREFIX',
            eng: 'all',
          },
          {
            c_type: 'SEED',
            eng: 'online sales',
          },
          {
            c_type: 'FILTER',
            eng: "'East' (Customer Region)",
          },
        ],
        row_limit: 50,
        condition_filter: ['East'],
      },
      reference_id: '1.1.210',
    },
  },
  {
    // 10. total sales by region by year
    data: {
      data: {
        sql: [''],
        chart_images: null,
        row_limit: 500,
        columns: [
          {
            groupable: true,
            is_visible: true,
            multi_series: false,
            display_name: 'Region',
            type: 'STRING',
            name: 'public.customer_dimension.customer_region',
          },
          {
            groupable: true,
            is_visible: true,
            multi_series: false,
            display_name: 'Year',
            type: 'DATE_STRING',
            name: "date_part('year', public.date_dimension.date)",
          },
          {
            groupable: false,
            is_visible: true,
            multi_series: false,
            display_name: 'Total Online Sales',
            type: 'DOLLAR_AMT',
            name: 'sum(online_sales.online_sales_fact.sales_dollar_amount)',
          },
        ],
        rows: [
          ['West', 2017, 19971506],
          ['West', 2006, 19897455],
          ['West', 2015, 19894714],
          ['West', 2018, 19794356],
          ['West', 2009, 19653976],
          ['West', 2014, 19598834],
          ['West', 2003, 19445007],
          ['West', 2007, 19407518],
          ['West', 2011, 19325340],
          ['West', 2008, 19273272],
          ['West', 2016, 19238300],
          ['West', 2013, 19224368],
          ['West', 2020, 19041143],
          ['West', 2005, 19039406],
          ['West', 2012, 18837249],
          ['West', 2019, 18819319],
          ['West', 2010, 18800366],
          ['West', 2004, 18753742],
          ['West', 2021, 17899891],
          ['East', 2006, 15340258],
          ['East', 2017, 15319348],
          ['East', 2014, 15210995],
          ['East', 2015, 15203510],
          ['East', 2009, 15119456],
          ['East', 2018, 15054280],
          ['East', 2003, 15002735],
          ['East', 2007, 14995371],
          ['East', 2013, 14936674],
          ['East', 2016, 14922368],
          ['East', 2008, 14918790],
          ['East', 2011, 14830746],
          ['East', 2020, 14671177],
          ['East', 2005, 14566359],
          ['East', 2019, 14487957],
          ['East', 2012, 14487265],
          ['East', 2010, 14390423],
          ['East', 2004, 14376770],
          ['South', 2017, 14374191],
          ['South', 2015, 14347684],
          ['South', 2006, 14213692],
          ['South', 2014, 14195034],
          ['South', 2018, 14191212],
          ['South', 2009, 14187942],
          ['South', 2008, 13952578],
          ['South', 2003, 13950217],
          ['South', 2007, 13917335],
          ['South', 2013, 13915911],
          ['South', 2016, 13868447],
          ['South', 2011, 13864334],
          ['East', 2021, 13821451],
          ['South', 2012, 13754829],
          ['South', 2005, 13746894],
          ['South', 2020, 13723161],
          ['South', 2019, 13633309],
          ['South', 2004, 13513952],
          ['South', 2010, 13466681],
          ['South', 2021, 12876416],
          ['MidWest', 2006, 12269901],
          ['West', 2022, 12205427],
          ['MidWest', 2017, 12184436],
          ['MidWest', 2015, 12156445],
          ['MidWest', 2018, 12118755],
          ['MidWest', 2014, 12099054],
          ['MidWest', 2009, 12043777],
          ['MidWest', 2007, 11901335],
          ['MidWest', 2003, 11892076],
          ['MidWest', 2020, 11880101],
          ['MidWest', 2016, 11812979],
          ['MidWest', 2013, 11809877],
          ['MidWest', 2005, 11794271],
          ['MidWest', 2008, 11770872],
          ['MidWest', 2011, 11755341],
          ['MidWest', 2012, 11674987],
          ['MidWest', 2010, 11656874],
          ['MidWest', 2019, 11526244],
          ['MidWest', 2004, 11430060],
          ['MidWest', 2021, 11018698],
          ['East', 2022, 9431913],
          ['South', 2022, 8765837],
          ['MidWest', 2022, 7432053],
          ['SouthWest', 2017, 7258878],
          ['SouthWest', 2014, 7105882],
          ['SouthWest', 2018, 7097241],
          ['SouthWest', 2006, 7096910],
          ['SouthWest', 2015, 7092227],
          ['SouthWest', 2009, 7090350],
          ['SouthWest', 2007, 7069080],
          ['SouthWest', 2011, 6991314],
          ['SouthWest', 2003, 6985058],
          ['SouthWest', 2008, 6970976],
          ['SouthWest', 2013, 6934971],
          ['SouthWest', 2016, 6925118],
          ['SouthWest', 2020, 6861453],
          ['SouthWest', 2005, 6807554],
          ['SouthWest', 2019, 6773259],
          ['SouthWest', 2010, 6763270],
          ['SouthWest', 2012, 6721755],
          ['SouthWest', 2004, 6650411],
          ['SouthWest', 2021, 6469223],
          ['SouthWest', 2022, 4411069],
          ['NorthWest', 2009, 2053936],
          ['NorthWest', 2015, 2030907],
          ['NorthWest', 2014, 2023969],
          ['NorthWest', 2017, 2018756],
          ['NorthWest', 2018, 2014906],
          ['NorthWest', 2006, 2008380],
          ['NorthWest', 2003, 1986403],
          ['NorthWest', 2011, 1978965],
          ['NorthWest', 2008, 1963678],
          ['NorthWest', 2016, 1944023],
          ['NorthWest', 2013, 1940942],
          ['NorthWest', 2020, 1939179],
          ['NorthWest', 2005, 1933225],
          ['NorthWest', 2007, 1914096],
          ['NorthWest', 2019, 1895927],
          ['NorthWest', 2012, 1892819],
          ['NorthWest', 2004, 1885700],
          ['NorthWest', 2010, 1878380],
          ['NorthWest', 2021, 1811857],
          ['NorthWest', 2022, 1248434],
        ],
        display_type: 'data',
        interpretation: 'total online sales by Region by Year',
        session_filter_locks: [],
        fe_req: {
          filters: [],
          source: 'dashboards.user',
          chart_images: 'exclude',
          page_size: null,
          orders: [],
          translation: TranslationTypes.EXCLUDE,
          test: false,
          disambiguation: [],
          text: 'Total online sales by region by year',
          session_filter_locks: [],
        },
        query_id: 'q_GRMmjoKXTX-fl8gC3Pj-yA',
        parsed_interpretation: [
          {
            c_type: 'PREFIX',
            eng: 'total',
          },
          {
            c_type: 'SEED',
            eng: 'online sales',
          },
          {
            c_type: 'GROUPBY',
            eng: 'by Region',
          },
          {
            c_type: 'GROUPBY',
            eng: 'by Year',
          },
        ],
        text: 'total online sales by region by year',
        condition_filter: [],
      },
      message: '',
      reference_id: '1.1.210',
    },
  },
  {
    // 11. Total onlines sales by region by customer
    data: {
      data: {
        rows: [
          ['Everdata', 'MidWest', 277579],
          ['Evercare', 'West', 275368],
          ['Vericore', 'West', 271074],
          ['Intratech', 'South', 236031],
          ['Metagen', 'West', 225312],
          ['Virtadata', 'West', 225113],
          ['Metacore', 'East', 217603],
          ['Bettercom', 'West', 215970],
          ['Intracore', 'MidWest', 205592],
          ['Virtamedia', 'MidWest', 197154],
          ['Intrahope', 'MidWest', 195968],
          ['Intracare', 'West', 195535],
          ['Foodtech', 'MidWest', 193717],
          ['Foodmedia', 'East', 191529],
          ['Intrastar', 'MidWest', 191189],
          ['Foodcorp', 'East', 190143],
          ['Bettercore', 'West', 185998],
          ['Virtatech', 'West', 184443],
          ['Veritech', 'West', 182048],
          ['Inishop', 'West', 181042],
          ['Betterdata', 'South', 179838],
          ['Vericare', 'East', 177763],
          ['Inicorp', 'MidWest', 175280],
          ['Inistar', 'West', 169083],
          ['Virtacom', 'East', 168323],
          ['Americom', 'South', 168002],
          ['Metadata', 'South', 165965],
          ['Goldmedia', 'West', 165712],
          ['Infocorp', 'East', 165089],
          ['Metatech', 'West', 164648],
          ['Intradata', 'West', 163865],
          ['Virtatech', 'East', 162977],
          ['Inigen', 'South', 162331],
          ['Goldgen', 'MidWest', 161116],
          ['Inicare', 'South', 161044],
          ['Ameridata', 'South', 160256],
          ['Metastar', 'SouthWest', 159963],
          ['Everdata', 'West', 156837],
          ['Metahope', 'West', 155586],
          ['Evercore', 'West', 154935],
          ['Infoshop', 'West', 154886],
          ['Intragen', 'West', 152649],
          ['Everstar', 'West', 152243],
          ['Evergen', 'East', 151330],
          ['Intramedia', 'MidWest', 148627],
          ['Ameridata', 'East', 148219],
          ['Goldcorp', 'MidWest', 147995],
          ['Bettercorp', 'West', 147652],
          ['Betterhope', 'East', 146336],
          ['Infohope', 'South', 145436],
        ],
        parsed_interpretation: [
          {
            c_type: 'PREFIX',
            eng: 'total',
          },
          {
            c_type: 'SEED',
            eng: 'online sales',
          },
          {
            c_type: 'GROUPBY',
            eng: 'by Customer Name',
          },
          {
            c_type: 'GROUPBY',
            eng: 'by Customer Region',
          },
        ],
        session_filter_locks: [],
        display_type: 'data',
        condition_filter: [],
        chart_images: null,
        sql: [''],
        columns: [
          {
            multi_series: false,
            is_visible: true,
            display_name: 'Customer Name',
            groupable: true,
            type: 'STRING',
            name: 'public.customer_dimension.customer_name',
          },
          {
            multi_series: false,
            is_visible: true,
            display_name: 'Customer Region',
            groupable: true,
            type: 'STRING',
            name: 'public.customer_dimension.customer_region',
          },
          {
            multi_series: false,
            is_visible: true,
            display_name: 'Total Online Sales',
            groupable: false,
            type: 'DOLLAR_AMT',
            name: 'sum(online_sales.online_sales_fact.sales_dollar_amount)',
          },
        ],
        query_id: 'q_zcOWrngkQiadAnmNGAYUKw',
        row_limit: 50,
        interpretation: 'total online sales by Customer Name by Customer Region',
        fe_req: {
          session_filter_locks: [],
          disambiguation: [],
          filters: [],
          chart_images: 'exclude',
          text: 'Total online sales by region by customer',
          source: 'dashboards.user',
          test: false,
          page_size: 50,
          orders: [],
          translation: TranslationTypes.EXCLUDE,
        },
        text: 'total online sales by region by customer',
      },
      message: 'Success',
      reference_id: '1.1.210',
    },
  },
]
