export const columnOptionsList = [
  'id', // Identifier for a column
  'title', // Required This is the title that will be displayed in the header for this column
  'field', // Required (not required in icon/button columns) this is the key for this column in the data array
  'visible', // (boolean, default', // true) determines if the column is visible. (see Column Visibility for more details)
  'hozAlign', // sets the horizontal text alignment for this column (left|center|right)
  'vertAlign', // sets the vertical text alignment for this column (top|middle|bottom)
  'headerHozAlign', // sets the horizontal text alignment for this columns header title (left|center|right)
  'width', // sets the width of this column, this can be set in pixels or as a percentage of total table width (if not set the system will determine the best)
  'minWidth', // sets the minimum width of this column, this should be set in pixels
  'maxWidth', // sets the maximum width of this column, this should be set in pixels
  'maxInitialWidth', // sets the maximum width of this column when it is first renderd, the user can then resize to above this (up to the maxWidth, if set) this should be set in pixels
  'widthGrow', // when using fitColumns layout mode, determines how much the column should grow to fill available space (see Table Layout for more details)
  'widthShrink', // when using fitColumns layout mode, determines how much the column should shrink to fit available space (see Table Layout for more details)
  'resizable', // set whether column can be resized by user dragging its edges (see Table Layout for more details)
  'frozen', // freezes the column in place when scrolling (see Frozen Columns for more details)
  'responsive', // an integer to determine when the column should be hidden in responsive mode (see Responsive Layout for more details)
  'tooltip', // sets the on hover tooltip for each cell in this column (see Formatting Data for more details)
  'cssClass', // sets css classes on header and cells in this column. (value should be a string containing space separated class names)
  'rowHandle', // sets the column as a row handle, allowing it to be used to drag movable rows. (see Movable Rows for more details)
  'htmlOutput', // show or hide column in the getHtml function output (see Retrieve Data as HTML Table for more details)
  'print', // show or hide column in the print output (see Printing for more details)
  'clipboard', // show or hide column in the clipboard output (see Clipboard for more details)
  'sorter', // determines how to sort data in this column (see Sorting Data for more details)
  'sorterParams', // additional parameters you can pass to the sorter(see Sorting Data for more details)
  'formatter', // set how you would like the data to be formatted (see Formatting Data for more details)
  'formatterParams', // additional parameters you can pass to the formatter(see Formatting Data for more details)
  'formatterPrint', // set how you would like the data to be formatted when the table is printed(see Formatting Data for more details)
  'formatterPrintParams', // additional parameters you can pass to the print formatter(see Formatting Data for more details)
  'formatterClipboard', // set how you would like the data to be formatted when copied to the clipboard(see Formatting Data for more details)
  'formatterClipboardParams', // additional parameters you can pass to the clipboard formatter(see Formatting Data for more details)
  'formatterHtmlOutput', // set how you would like the data to be formatted when the getHtml function is used(see Formatting Data for more details)
  'formatterHtmlOutputParams', // additional parameters you can pass to the html output formatter(see Formatting Data for more details)
  'variableHeight', // alter the row height to fit the contents of the cell instead of hiding overflow
  'editable', // callback to check if the cell is editable (see Manipulating Data for more details)
  'editor', // set the editor to be used when editing the data. (see Manipulating Data for more details)
  'editorParams', // additional parameters you can pass to the editor (see Manipulating Data for more details)
  'validator', // set the validator to be used to approve data when a user edits a cell. (see Manipulating Data for more details)
  'contextMenu', // add context menu to column cells (see Cell Menus for more details)
  'clickMenu', // add left click menu to column cells (see Cell Menus for more details)
  'dblClickMenu', // add double left click menu to column cells (see Cell Menus for more details)
  'contextPopup', // add context popup to column cells (see Cell Popups for more details)
  'clickPopup', // add left click popup to column cells (see Cell Popups for more details)
  'dblClickPopup', // add double left click popup to column cells (see Cell Popups for more details)
  'mutator', // function for manipulating column values as they are parsed into the table (see Mutators for more details)
  'mutatorParams', // additional parameters you can pass to the mutator(see Mutators for more details)
  'mutatorData', // function for manipulating column values as they are parsed into the table by command (see Mutators for more details)
  'mutatorDataParams', // additional parameters you can pass to the mutatorData(see Mutators for more details)
  'mutatorEdit', //  - function for manipulating column values as they are edited by a user (see Mutators for more details)
  'mutatorEditParams', //  - additional parameters you can pass to the mutatorEdit(see Mutators for more details)
  'mutatorClipboard', //  - function for manipulating column values as they are pasted by a user (see Mutators for more details)
  'mutatorClipboardParams', //  - additional parameters you can pass to the mutatorClipboard (see Mutators for more details)
  'mutateLink', //  - trigger mutation on columns when this column is edited (see Mutators for more details)
  'accessor', //  - function to alter column values before they are extracted from the table function (see Accessors for more details)
  'accessorParams', //  - additional parameters you can pass to the accessor(see Accessors for more details)
  'accessorData', //  - function to alter column values before they are extracted from the table using the getData function (see Accessors for more details)
  'accessorDataParams', //  - additional parameters you can pass to the accessorData(see Accessors for more details)
  'accessorDownload', //  - function to alter column values before they are included in a file download (see Accessors for more details)
  'accessorDownloadParams', //  - additional parameters you can pass to the accessorDownload(see Accessors for more details)
  'accessorClipboard', //  - function to alter column values before they are copied to the clipboard (see Accessors for more details)
  'accessorClipboardParams', //  - additional parameters you can pass to the accessorClipboard(see Accessors for more details)
  'download', //  - show or hide column in downloaded data (see Downloading Table Data for more details)
  'titleDownload', //  - set custom title for column in download (see Downloading Table Data for more details)
  'topCalc', //  - the column calculation to be displayed at the top of this column(see Column Calculations for more details)
  'topCalcParams', //  - additional parameters you can pass to the topCalc calculation function (see Column Calculations for more details)
  'topCalcFormatter', //  - formatter for the topCalc calculation cell (see Column Calculations for more details)
  'topCalcFormatterParams', //  - additional parameters you can pass to the topCalcFormatter function(see Column Calculations for more details)
  'bottomCalc', //  - the column calculation to be displayed at the bottom of this column(see Column Calculations for more details)
  'bottomCalcParams', //  - additional parameters you can pass to the bottomCalc calculation function(see Column Calculations for more details)
  'bottomCalcFormatter', //  - formatter for the bottomCalc calculation cell (see Column Calculations for more details)
  'bottomCalcFormatterParams', //  - additional parameters you can pass to the bottomCalcFormatter function(see Column Calculations for more details)
  'cellClick', //  - callback for when user clicks on a cell in this column (see Callbacks for more details)
  'cellDblClick', //  - callback for when user double clicks on a cell in this column (see Callbacks for more details)
  'cellContext', //  - callback for when user right clicks on a cell in this column (see Callbacks for more details)
  'cellTap', //  - callback for when user taps on a cell in this column, triggered in touch displays. (see Callbacks for more details)
  'cellDblTap', //  - callback for when user double taps on a cell in this column, triggered in touch displays when a user taps the same cell twice in under 300ms. (see Callbacks for more details)
  'cellTapHold', //  - callback for when user taps and holds on a cell in this column, triggered in touch displays when a user taps and holds the same cell for 1 second. (see Callbacks for more details)
  'cellMouseEnter', //  - callback for when the mouse pointer enters a cell (see Callbacks for more details)
  'cellMouseLeave', //  - callback for when the mouse pointer leaves a cell (see Callbacks for more details)
  'cellMouseOver', //  - callback for when the mouse pointer enters a cell or one of its child elements(see Callbacks for more details)
  'cellMouseOut', //  - callback for when the mouse pointer enters a cell or one of its child elements(see Callbacks for more details)
  'cellMouseMove', //  - callback for when the mouse pointer moves over a cell (see Callbacks for more details)
  'cellMouseDown', //  - callback for the left mouse button is pressed with the cursor over a cell (see Callbacks for more details)
  'cellMouseUp', //  - callback for the left mouse button is released with the cursor over a cell (see Callbacks for more details)
  'cellEditing', //  - callback for when a cell in this column is being edited by the user (see Callbacks for more details)
  'cellEdited', //  - callback for when a cell in this column has been edited by the user (see Callbacks for more details)
  'cellEditCancelled', //  - callback for when an edit on a cell in this column is aborted by the user (see Callbacks for more details)
  'headerSort', // user can sort by clicking on the header (see Sorting Data for more details)
  'headerSortStartingDir', // set the starting sort direction when a user first clicks on a header (see Sorting Data for more details)
  'headerSortTristate', // allow tristate toggling of column header sort direction (see Sorting Data for more details)
  'headerClick', // callback for when user clicks on the header for this column (see Callbacks for more details)
  'headerDblClick', // callback for when user double clicks on the header for this column (see Callbacks for more details)
  'headerContext', // callback for when user right clicks on the header for this column (see Callbacks for more details)
  'headerTap', // callback for when user taps on a header for this column, triggered in touch displays. (see Callbacks for more details)
  'headerDblTap', // callback for when user double taps on a header for this column, triggered in touch displays when a user taps the same header twice in under 300ms. (see Callbacks for more details)
  'headerTapHold', // callback for when user taps and holds on a header for this column, triggered in touch displays when a user taps and holds the same header for 1 second. (see Callbacks for more details)
  'headerMouseEnter', // callback for when the mouse pointer enters a column header (see Callbacks for more details)
  'headerMouseLeave', // callback for when the mouse pointer leaves a column header (see Callbacks for more details)
  'headerMouseOver', // callback for when the mouse pointer enters a column header or one of its child elements(see Callbacks for more details)
  'headerMouseOut', // callback for when the mouse pointer enters a column header or one of its child elements(see Callbacks for more details)
  'headerMouseMove', // callback for when the mouse pointer moves over a column header (see Callbacks for more details)
  'headerMouseDown', // callback for the left mouse button is pressed with the cursor over a column header (see Callbacks for more details)
  'headerMouseUp', // callback for the left mouse button is released with the cursor over a column header (see Callbacks for more details)
  'headerTooltip', // sets the on hover tooltip for the column header (see Formatting Data for more details)
  'headerVertical', // change the orientation of the column header to vertical (see Vertical Column Headers for more details)
  'editableTitle', // allows the user to edit the header titles. (see Editable Column Titles for more details)
  'titleFormatter', // formatter function for header title (see Formatting Data for more details)
  'titleFormatterParams', // additional parameters you can pass to the header title formatter(see Formatting Data for more details)
  'headerWordWrap', // Allow word wrapping in the column header (see Header Text Wrapping for more details)
  'headerFilter', // filtering of columns from elements in the header (see Header Filtering for more details)
  'headerFilterPlaceholder', // placeholder text for the header filter (see Header Filtering for more details)
  'headerFilterParams', // additional parameters you can pass to the header filter (see Header Filtering for more details)
  'headerFilterEmptyCheck', // function to check when the header filter is empty (see Header Filtering for more details)
  'headerFilterFunc', // the filter function that should be used by the header filter (see Header Filtering for more details)
  'headerFilterFuncParams', // additional parameters object passed to the headerFilterFunc function (see Header Filtering for more details)
  'headerFilterLiveFilter', // disable live filtering of the table (see Header Filtering for more details)
  'headerMenu', // add menu button to column header (see Header Menus for more details)
  'headerClickMenu', // add click menu to column header (see Header Menus for more details)
  'headerDblClickMenu', // add double click menu to column header (see Header Menus for more details)
  'headerContextMenu', // add context menu to column header (see Header Menus for more details)
  'headerPopup', // add popup button to column header (see Column Header Popups for more details)
  'headerClickPopup', // add click popup to column header (see Column Header Popups for more details)
  'headerContextPopup', // add context popup to column header (see Column Header Popups for more details)
  'groupable', // allow the column to be grouped (see Grouping Data for more details)
]
