steps:
  - name: "tarampampam/node:14-alpine"
    id: build-and-test
    entrypoint: /bin/bash
    args:
      - "-exc"
      - |
        ls al
        pwd

    secretEnv: ["NPM_TOKEN", "GH_TOKEN"]

  # # This step Test & Release widgets
  # - name: "us.gcr.io/$PROJECT_ID/gcp-azure-base:v1"
  #   id: Test and Release react-autoql npm package
  #   entrypoint: /bin/bash
  #   args:
  #     - "-exc"
  #     - |
  #       PROJECT_ID=$PROJECT_ID BUILD_ID=$BUILD_ID COMMIT_SHA=$COMMIT_SHA REVISION_ID=$REVISION_ID SHORT_SHA=$SHORT_SHA REPO_NAME=$REPO_NAME BRANCH_NAME=$BRANCH_NAME TAG_NAME=$TAG_NAME
  #       _DEBUG=$_DEBUG
  #       [ -f ./config/cloudbuild_before_release.sh ] && source ./config/cloudbuild_before_release.sh
  #       source ./config/cloudbuild_release.sh
  #   secretEnv:
  #     [
  #       "npm_token",
  #       "gh_token",
  #       "azure_sp_secret",
  #       "azure_sp_username",
  #       "azure_sp_tenantid",
  #       "cloudbuild_msg_repo",
  #       "cloudbuild_msg_pubsub_topic",
  #     ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/npm_token/versions/latest
      env: "NPM_TOKEN"
    - versionName: projects/$PROJECT_NUMBER/secrets/gh_token/versions/latest
      env: "GH_TOKEN"
options:
  substitution_option: "ALLOW_LOOSE"

timeout: 14400s

tags:
  [
    "$REPO_NAME",
    "$COMMIT_SHA",
    "$SHORT_SHA",
    "$PROJECT_ID",
    "$BRANCH_NAME",
    "$TAG_NAME",
    "$REVISION_ID",
    "$BUILD_ID",
  ]
