/**
 * Captured session payloads, used by the mock mode the `enableMockResponses` prop
 * turns on. The real /sessions endpoints aren't live yet, so this is what lets the
 * messenger be developed and reviewed against realistic content.
 *
 * Kept as a JS module rather than JSON because the rollup build has no JSON plugin -
 * and it is the single source for both the mock mode and the tests, so the two can't
 * drift apart.
 */

// POST /autoql/api/v1/sessions - carries the new session_id plus one text item.
export const MOCK_CREATE_SESSION_RESPONSE = {
  session_id: 'efe31e82-4e81-4b07-8d58-06fbc6557296',
  response_items: [
    {
      type: 'text',
      data: {
        text: 'Yes. To make the comparison precise, please confirm:\n\n1. Does **Eagles** mean the team listed as “Eagles” in the data?\n2. Which two **season years** should I use for “last season” and “the season before”? (The available data includes a `season` field, but I should not assume the latest year.)\n3. What should “performance” include? I can compare record, scoring (points for/against), and team offensive statistics such as total yards, first downs, turnovers, rushing, and passing—or focus on specific measures you prefer.\n\nI can present the results as a season-by-season comparison table with absolute and percentage changes, plus a short takeaway.',
      },
    },
  ],
}

// POST /autoql/api/v1/sessions/{id}/resume - no session_id, and a 22-column table
// followed by the commentary about it.
export const MOCK_RESUME_SESSION_RESPONSE = {
  response_items: [
    {
      type: 'table',
      data: {
        columns: [
          {
            display_name: 'Game Date',
            dow_style: 'ALPHA_MON',
            type: 'DATE',
            precision: 'DAY',
          },
          {
            display_name: 'Season',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Season Type',
            dow_style: 'ALPHA_MON',
            type: 'STRING',
            precision: '',
          },
          {
            display_name: 'Score',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Opposition Score',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Total Plays',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Total Yards',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'First Downs',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Turnovers',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Rushing Attempts',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Rushing Yards',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Rushing Touchdowns',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Passing Attempts',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Passing Yards',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Passing Touchdowns',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Receiving Yards',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Receiving Touchdowns',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Receptions',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Two Point Conversion Attempts',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Two Point Conversion Succeeded',
            dow_style: 'ALPHA_MON',
            type: 'QUANTITY',
            precision: '',
          },
          {
            display_name: 'Opposition Team',
            dow_style: 'ALPHA_MON',
            type: 'STRING',
            precision: '',
          },
          {
            display_name: 'Team',
            dow_style: 'ALPHA_MON',
            type: 'STRING',
            precision: '',
          },
        ],
        rows: [
          [
            '2026-01-04',
            2025,
            'Regular Season',
            17,
            24,
            62,
            307,
            18,
            1,
            19,
            80,
            1,
            40,
            241,
            1,
            241,
            1,
            21,
            0,
            0,
            'Washington Commanders',
            'Philadelphia Eagles',
          ],
          [
            '2025-12-28',
            2025,
            'Regular Season',
            13,
            12,
            190,
            190,
            11,
            0,
            26,
            82,
            0,
            27,
            110,
            1,
            110,
            1,
            13,
            0,
            0,
            'Buffalo Bills',
            'Philadelphia Eagles',
          ],
          [
            '2025-12-20',
            2025,
            'Regular Season',
            29,
            18,
            385,
            385,
            26,
            1,
            34,
            207,
            2,
            30,
            185,
            2,
            185,
            2,
            22,
            1,
            1,
            'Washington Commanders',
            'Philadelphia Eagles',
          ],
          [
            '2025-12-14',
            2025,
            'Regular Season',
            31,
            0,
            66,
            387,
            27,
            0,
            47,
            183,
            1,
            18,
            208,
            3,
            208,
            3,
            15,
            0,
            0,
            'Las Vegas Raiders',
            'Philadelphia Eagles',
          ],
          [
            '2025-12-08',
            2025,
            'Regular Season',
            19,
            22,
            365,
            365,
            19,
            5,
            25,
            134,
            1,
            40,
            240,
            0,
            240,
            0,
            21,
            0,
            0,
            'Los Angeles Chargers',
            'Philadelphia Eagles',
          ],
          [
            '2025-11-28',
            2025,
            'Regular Season',
            15,
            24,
            51,
            317,
            14,
            2,
            17,
            87,
            0,
            34,
            230,
            2,
            230,
            2,
            19,
            1,
            0,
            'Chicago Bears',
            'Philadelphia Eagles',
          ],
          [
            '2025-11-23',
            2025,
            'Regular Season',
            21,
            24,
            339,
            339,
            19,
            2,
            18,
            63,
            2,
            39,
            289,
            1,
            289,
            1,
            27,
            0,
            0,
            'Dallas Cowboys',
            'Philadelphia Eagles',
          ],
          [
            '2025-11-16',
            2025,
            'Regular Season',
            16,
            9,
            69,
            272,
            16,
            0,
            40,
            148,
            1,
            28,
            135,
            0,
            135,
            0,
            14,
            0,
            0,
            'Detroit Lions',
            'Philadelphia Eagles',
          ],
          [
            '2025-11-10',
            2025,
            'Regular Season',
            10,
            7,
            294,
            294,
            13,
            1,
            34,
            111,
            0,
            26,
            183,
            1,
            183,
            1,
            15,
            0,
            0,
            'Green Bay Packers',
            'Philadelphia Eagles',
          ],
          [
            '2025-10-26',
            2025,
            'Regular Season',
            38,
            20,
            57,
            427,
            23,
            0,
            33,
            276,
            1,
            20,
            179,
            4,
            179,
            4,
            15,
            0,
            0,
            'New York Giants',
            'Philadelphia Eagles',
          ],
          [
            '2025-10-19',
            2025,
            'Regular Season',
            28,
            22,
            361,
            361,
            13,
            0,
            23,
            45,
            0,
            23,
            326,
            3,
            326,
            3,
            19,
            0,
            0,
            'Minnesota Vikings',
            'Philadelphia Eagles',
          ],
          [
            '2025-10-09',
            2025,
            'Regular Season',
            17,
            34,
            339,
            339,
            20,
            2,
            20,
            73,
            1,
            33,
            283,
            1,
            283,
            1,
            24,
            0,
            0,
            'New York Giants',
            'Philadelphia Eagles',
          ],
          [
            '2025-10-05',
            2025,
            'Regular Season',
            17,
            21,
            55,
            302,
            16,
            0,
            11,
            45,
            0,
            38,
            280,
            2,
            280,
            2,
            23,
            0,
            0,
            'Denver Broncos',
            'Philadelphia Eagles',
          ],
          [
            '2025-09-28',
            2025,
            'Regular Season',
            31,
            25,
            200,
            200,
            16,
            0,
            32,
            88,
            1,
            24,
            130,
            2,
            130,
            2,
            15,
            0,
            0,
            'Tampa Bay Buccaneers',
            'Philadelphia Eagles',
          ],
          [
            '2025-09-21',
            2025,
            'Regular Season',
            33,
            26,
            63,
            288,
            19,
            1,
            27,
            86,
            1,
            32,
            226,
            3,
            226,
            3,
            21,
            1,
            0,
            'Los Angeles Rams',
            'Philadelphia Eagles',
          ],
          [
            '2025-09-14',
            2025,
            'Regular Season',
            20,
            17,
            216,
            216,
            16,
            0,
            34,
            122,
            2,
            22,
            101,
            0,
            101,
            0,
            15,
            0,
            0,
            'Kansas City Chiefs',
            'Philadelphia Eagles',
          ],
          [
            '2025-09-04',
            2025,
            'Regular Season',
            24,
            20,
            62,
            302,
            20,
            0,
            38,
            158,
            3,
            23,
            152,
            0,
            152,
            0,
            19,
            0,
            0,
            'Dallas Cowboys',
            'Philadelphia Eagles',
          ],
        ],
      },
    },
    {
      type: 'text',
      data: {
        text: 'Here are the game-level offensive team statistics for the Eagles in the 2025 and 2026 seasons (regular season and postseason). Please review the data and confirm that it meets your expectations. Once confirmed, I will move on to the season-by-season comparison and provide both the table and narrative analysis.',
      },
    },
  ],
}

// Normalized the same way sessionService does, so mock mode and the real request path
// hand the reducer an identical shape.
export const getMockSessionResponse = (isNewSession) => {
  const payload = isNewSession ? MOCK_CREATE_SESSION_RESPONSE : MOCK_RESUME_SESSION_RESPONSE

  return {
    sessionId: payload.session_id ?? null,
    responseItems: payload.response_items,
  }
}
