export const LIGHT_THEME = {
  'accent-color': '#28A8E0',
  'accent-color-secondary': '#1EA0D8',
  'background-color-primary': '#F8F8F8',
  'background-color-secondary': '#FFFFFF',
  'background-color-tertiary': '#E8E8E8',
  'background-color-switch-input': '#BABABA',
  'background-color-switch-thumb': '#FFFFFF',
  'background-color-disabled': '#EDEDED',
  'background-color-disabled-dark': '#857D83',
  'background-color-checkbox': '#FFFFFF',
  'border-color': '#D8D8D8',
  'table-border-color': '#EFEFEF',
  'hover-color': '#F6F7F9',
  'text-color-primary': '#343434',
  'text-color-accent': '#FFFFFF',
  'text-color-placeholder': '#0000004D',
  'dashboard-title-color': '#28A8E0',
  'font-family': "'Roboto', sans-serif",
  'font-size': '15px',
  'chart-font-size': '12px',
  'highlight-color': '#000000',
  'badge-color': '#F5222D',
  'danger-color': '#CA0B00',
  'warning-color': '#FFB600',
  'success-color': '#47b84c',
  'info-color': '#28A8E0',
  'box-shadow-color': '#85858528',
  'mask-color': '#0000000F',
  'mobile-mask-color': '#00000059',
  'scrollbar-color': '#aeaeae',
  'box-shadow-1': '0px 1px 2px 1px var(--react-autoql-box-shadow-color)',
  'box-shadow-2': '0px 1px 2px 0px var(--react-autoql-box-shadow-color)',
}

export const DARK_THEME = {
  'accent-color': '#193a48',
  'accent-color-secondary': '#1ea0d8',
  'background-color-primary': '#20252A',
  'background-color-secondary': '#3B3F46',
  'background-color-tertiary': '#292929',
  'background-color-switch-input': '#252525',
  'background-color-switch-thumb': '#ececec',
  'background-color-checkbox': '#292929',
  'background-color-disabled': '#5d6167',
  'background-color-disabled-dark': '#857d83',
  'table-border-color': '#53565c',
  'border-color': '#53565c',
  'hover-color': '#4a4f56',
  'text-color-primary': '#ececec',
  'text-color-accent': '#ffffff',
  'text-color-placeholder': '#ffffff6e',
  'dashboard-title-color': '#193a48',
  'font-family': "'Roboto', sans-serif",
  'font-size': '12px',
  'chart-font-size': '12px',
  'highlight-color': '#ffffff',
  'badge-color': '#f5222d',
  'danger-color': '#ff584e',
  'warning-color': '#ffcc00',
  'success-color': '#47b84c',
  'info-color': '#28a8e0',
  'box-shadow-color': '#00000066',
  'mask-color': '#00000021',
  'mobile-mask-color': '#00000059',
  'scrollbar-color': '#727477',
  'box-shadow-1': '0px 1px 1px 0px var(--react-autoql-box-shadow-color)',
  'box-shadow-2': '0px 1px 2px 0px var(--react-autoql-box-shadow-color)',
}
