export const LIGHT_THEME = {
  'accent-color': '#28a8e0',
  'accent-color-secondary': '#1ea0d8',
  'background-color-primary': '#F1F3F5',
  'background-color-secondary': '#ffffff',
  'background-color-tertiary': '#e8e8e8',
  'background-color-checkbox': '#cccccc',
  'background-color-disabled': '#ededed',
  'background-color-disabled-dark': '#857d83',
  'background-color-checkbox': '#ffffff',
  'border-color': '#d8d8d8',
  'hover-color': '#f6f7f9',
  'text-color-primary': '#4f4f4f',
  'text-color-accent': '#ffffff',
  'text-color-placeholder': '#0000004d',
  'dashboard-title-color': '#28a8e0',
  'font-family': 'sans-serif',
  'highlight-color': '#000000',
  'danger-color': '#ca0b00',
  'warning-color': '#ffcc00',
  'success-color': '#2aca4d',
  'info-color': '#28a8e0',
  'box-shadow-color': '#00000026',
  'mask-color': '#0000000f',
}

export const DARK_THEME = {
  'accent-color': '#193a48',
  'accent-color-secondary': '#1ea0d8',
  'background-color-primary': '#20252A',
  'background-color-secondary': '#3B3F46',
  'background-color-tertiary': '#292929',
  'background-color-checkbox': '#292929',
  'background-color-disabled': '#5d6167',
  'background-color-disabled-dark': '#857d83',
  'border-color': '#53565c',
  'hover-color': '#4a4f56',
  'text-color-primary': '#ececec',
  'text-color-accent': '#ffffff',
  'text-color-placeholder': '#ffffff6e',
  'dashboard-title-color': '#193a48',
  'font-family': 'sans-serif',
  'highlight-color': '#ffffff',
  'danger-color': '#ff584e',
  'warning-color': '#ffcc00',
  'success-color': '#2aca4d',
  'info-color': '#28a8e0',
  'box-shadow-color': '#00000066',
  'mask-color': '#00000021',
}
