export const LIGHT_THEME = {
  'accent-color': '#28a8e0',
  'background-color-primary': '#ffffff',
  'background-color-secondary': '#F1F3F5',
  'background-color-tertiary': '#cccccc',
  'border-color': '#e6e6e6',
  'hover-color': '#ececec',
  'text-color-primary': '#4f4f4f',
  'accent-text-color': '#ffffff',
  'text-color-placeholder': '#0000005e',
  'dashboard-title-color': '#28a8e0',
  'font-family': 'sans-serif',
  'highlight-color': '#000000',
  'danger-color': '#ca0b00',
  'warning-color': '#ffcc00',
  'success-color': '#2aca4d',
}

export const DARK_THEME = {
  'accent-color': '#193a48', // dark blue
  'background-color-primary': '#3B3F46',
  'background-color-secondary': '#20252A',
  'background-color-tertiary': '#292929',
  'border-color': '#53565c',
  'hover-color': '#4a4f56',
  'text-color-primary': '#ececec',
  'accent-text-color': '#ffffff',
  'text-color-placeholder': '#ffffff9c',
  'dashboard-title-color': '#193a48',
  'font-family': 'sans-serif',
  'highlight-color': '#ffffff',
  'danger-color': '#ff584e',
  'warning-color': '#ffcc00',
  'success-color': '#2aca4d',
}
