on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    uses: peterjgrainger/action-create-branch@v2.0.1
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      branch: 'NikkiMeganMoore-patch-1'
